name: CI Test C++

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Compilar test
        run: g++ test.cpp -o test

      - name: Ejecutar test
        run: ./test