name: CI C++

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Compilar
        run: g++ main.cpp -o app

      - name: Ejecutar
        run: ./app
